// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const _: typeof import('lodash')['_']
  const moment: typeof import('moment')['default']
}
export {}
